set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g mouse on

set -g status-style bg='#1a1b26',fg='#33ccff'
set -g status-left '#[fg=#1a1b26,bg=#33ccff,bold]  #S '
set -g status-right '#[fg=#33ccff,bg=#1a1b26] %H:%M |  '

set -g pane-border-style fg='#414868'

set -g base-index 1
setw -g pane-base-index 1
