# BACKGROUND
background {
    monitor =
    path = ~/.config/hypr/hyprlock.jpg
    blur_passes = 1
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.8172
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# Profile-Photo
image {
    monitor =
    path = ~/.config/hypr/profile.jpg
    border_size = 2
    border_color = rgba(51, 204, 255, 0.80)
    size = 100
    rounding = -1
    rotate = 0
    reload_time = -1
    position = 25, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(216, 222, 233, 0.80)
    font_size = 22
    font_family = JetBrainsMono Nerd Font Bold
    position = 25, 110
    halign = center
    valign = center
}

# HEURE (Format 24h)
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = rgba(216, 222, 233, 0.80)
    font_size = 65
    font_family = JetBrainsMono Nerd Font Bold
    position = 30, -8
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo -e "$(LC_TIME=fr_FR.UTF-8 date +"%A %d %B")"
    color = rgba(216, 222, 233, .80)
    font_size = 20
    font_family = JetBrainsMono Nerd Font Bold
    position = 35, -65
    halign = center
    valign = center
}

shape {
    monitor =
    size = 320, 55
    color = rgba(255, 255, 255, 0.05)
    rounding = -1
    border_size = 1
    border_color = rgba(51, 204, 255, 0.3)
    position = 34, -190
    halign = center
    valign = center
}

label {
    monitor =
    text =   $USER
    color = rgba(216, 222, 233, 0.80)
    font_size = 16
    font_family = JetBrainsMono Nerd Font Bold
    position = 38, -190
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 55
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(51, 204, 255, 0.6)
    inner_color = rgba(0, 0, 0, 0.6)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font Bold
    placeholder_text = <i><span foreground="##ffffff99">🔒 Entrez le mot de passe...</span></i>
    hide_input = false
    position = 34, -268
    halign = center
    valign = center
    
    # Couleurs de feedback
    check_color = rgba(51, 204, 255, 1.0)
    fail_color = rgba(255, 85, 85, 1.0)
    fail_text = <i>Mauvais mot de passe ($ATTEMPTS)</i>
}