add_newline = false

format = """
$os\
$directory\
$git_branch\
$git_status\
$docker_context\
$fill\
$cmd_duration\
$line_break\
$character"""

[os]
disabled = false
format = "[$symbol]($style) "
style = "bold #33ccff"

[os.symbols]
Arch = "󰣇"

[directory]
style = "bold #7aa2f7"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bold #bb9af7"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold #f7768e"
format = '([\[$all_status$ahead_behind\]]($style) )'

[docker_context]
symbol = " "
style = "bold #0db7ed"
format = "at [$symbol$context]($style) "

[fill]
symbol = " "

[cmd_duration]
min_time = 500
format = "took [$duration]($style)"
style = "fg:#565f89"

[character]
success_symbol = "[󰄾](bold #33ccff) "
error_symbol = "[󰄾](bold #f7768e) "
